name: my-first-workflow
on:
  push:
    branches:
      - main
      - dev
      - 'feature-*'
  workflow_dispatch:
  pull_request:
    branches:
      - main
env:
  ENV_ZONE: dev
  APP_USER: ap
  APP_PORT: 80

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: step-2-checkout
        uses: actions/checkout@v7.0.1
      - name: step-3
        run: |
          pwd
          echo 'Hi this is artifact upload test file' >> myartifact.txt 
          ls -ltr
          hostname
      - name: Upload single File
        uses: actions/upload-artifact@v7.0.1
        with:
          name: single_file
          path: ./myartifact.txt
      - name: Download  artifacts
        uses: actions/download-artifact@v8.0.0
        with:
          name: single_file
          path: ./downloaded_directory
      - name: Test downloaded file
        run: |
          ls -ltr
          cd downloaded_directory
          ls -ltr 
          cat myartifact.txt

  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: test env's
        run: |
          echo "[INFO] Running the job on $ENV_ZONE with user $APP_USER"
          echo "[INFO] The AWS acount id is : ${{ secrets.AWS_ACCOUNT_ID }}"
          echo "[INFO] ${{ github.ref }} "

  Dev_Deployment:
    name: development
    runs-on: ubuntu-latest
    steps:
      - name: test evnironments
        run: |
          echo "[INFO] running DEV_ENVIRONMENT with user ${{ vars.USER }} on port ${{ vars.PORT }}"
          echo "[INFO] AWS account is ${{ secrets.AWS_ACCOUNT_ID }}"
    environment:
      name: DEV
    if: github.ref == 'dev'

  PROD_DEPLOYMETN:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Test PROD Environment
        run: |
          echo "[INFO] User ${{ vars.HOST }} is running the Production deployment on port ${{ vars.port }}"

    environment:
      name: PROD
    if: github.ref == 'refs/heads/main'
