name: my-first-workflow
on: push
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: running single command on job1
        run: echo "Hello This Is my first job"
      - name: checking os Release for github Hosted Runner
        run: cat /etc/os-release
      - name: running sleep
        run: sleep 5
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - name: Checking the hostname for runner
        run: hostname
      - name: Running multiple commands
        run: | 
            echo "Hi from AP"
            echo "Current time is  `date`"
  job3:
    name: job3
    runs-on: macos-12
    steps:
      - name: Installing tree using homebrew
        run: |
          brew install tree

  job4:
    name : job4
    needs: job3
    runs-on: macos-12
    steps:
      - name: Test tree installation
        run: tree--version

